import { StyleSheet } from 'react-native'

export const colors = {
  bg: '#0b1220',
  card: '#0f172a',
  border: 'rgba(148,163,184,0.25)',
  text: '#e5e7eb',
  muted: '#9ca3af',
  danger: '#f87171',
  primary: '#38bdf8',
  primaryText: '#001018',
  textStrong: '#f8fafc',
  surface: 'rgba(15,23,42,0.3)',
}

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.bg,
    padding: 16,
  },
  screenCentered: {
    flex: 1,
    backgroundColor: colors.bg,
    padding: 16,
    justifyContent: 'center',
  },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 22,
    paddingVertical: 24,
    paddingHorizontal: 20,
  },
  brandMark: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 2.4,
    textTransform: 'uppercase',
    color: colors.text,
    marginBottom: 18,
  },
  heroTitle: {
    fontSize: 42,
    fontWeight: '600',
    lineHeight: 44,
    letterSpacing: -1.2,
    color: colors.textStrong,
    marginBottom: 14,
  },
  title: {
    fontSize: 26,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: colors.muted,
    marginBottom: 16,
    lineHeight: 20,
  },
  heroText: {
    fontSize: 14,
    color: colors.muted,
    marginBottom: 18,
    lineHeight: 20,
  },
  logoWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 18,
  },
  logoCircle: {
    width: 220,
    height: 220,
    borderRadius: 110,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoImage: {
    width: 190,
    height: 190,
    resizeMode: 'contain',
  },
  label: {
    fontSize: 13,
    color: colors.text,
    marginBottom: 6,
  },
  input: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.text,
    marginBottom: 12,
    backgroundColor: colors.surface,
  },
  row: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  buttonPrimary: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  buttonSecondary: {
    borderColor: colors.border,
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  buttonTextPrimary: {
    color: colors.primaryText,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  buttonTextSecondary: {
    color: colors.text,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  error: {
    color: colors.danger,
    marginBottom: 12,
  },
  code: {
    color: colors.text,
    fontFamily: 'monospace',
  },
})

